### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nunojesus** [0x1C1B/SunriseOS#1]
Hi, How are you?
Im a graphic designer that like to help projects in opensource for free, so if you like I can contribute with graphic designs,, I can make you a logotype for this project if you want, I like very much your project is amazing!
So if you need some design just say it.

Greetings!
Nuno Jesus

**Comment by 0x1C1B** [comment]
I stopped active development of this project! If you want you can still create an icon for it, I will add it.
But this project and it's source is absolutely free for everyone now!

**Comment by 0x1C1B** [comment]
But if you still want to design a logo for one of my other projects / repositories I would be very glad. Specially the [JContacts](https://github.com/0x1C1B/JContacts) project should be finalized ultimately for a final release, your work will be welcome!
